
from mapping import create_prediction_visualizations


RandomForestCoordinates="/home/vfourel/SOCProject/SOCmapping/results_prediction_41by41WindowSize/RandomForest/2015Inference/coordinates_1mil.npy"
RandomForestPredictions="/home/vfourel/SOCProject/SOCmapping/results_prediction_41by41WindowSize/RandomForest/2015Inference/predictions_1mil.npy"
XGBoostCoordinates="/home/vfourel/SOCProject/SOCmapping/results_prediction_41by41WindowSize/XGBoost/2015Inference/coordinates_1mil.npy"
XGBoostPredictions="/home/vfourel/SOCProject/SOCmapping/results_prediction_41by41WindowSize/XGBoost/2015Inference/predictions_1mil.npy"
_2DCNNCoordinates="/home/vfourel/SOCProject/SOCmapping/2DCNN/finalResult/coordinates_1mil.npy"
_2DCNNPredictions="/home/vfourel/SOCProject/SOCmapping/2DCNN/finalResult/predictions_1mil.npy"
_3DCNNCoordinates="/home/vfourel/SOCProject/SOCmapping/3DCNN/finalResults/coordinates_1mil.npy"
_3DCNNPredictions="/home/vfourel/SOCProject/SOCmapping/3DCNN/finalResults/predictions_1mil.npy"
CNNLSTMCoordinates="/home/vfourel/SOCProject/SOCmapping/CNNLSTM/finalResults/coordinates_1mil.npy"
CNNLSTMPredictions="/home/vfourel/SOCProject/SOCmapping/CNNLSTM/finalResults/predictions_1mil.npy"
TemporalFusionTransformerPredictions="/home/vfourel/SOCProject/SOCmapping/TemporalFusionTransformer/finalResults/concatenatedResults/predictions.npy"
TemporalFusionTransformerCoordinates="/home/vfourel/SOCProject/SOCmapping/TemporalFusionTransformer/finalResults/concatenatedResults/coordinates.npy"
_2milTransformerCoordinates="/home/vfourel/SOCProject/SOCmapping/SimpleTransformer/final_transformer_model_MAX_OC_150_TIME_BEGINNING_2007_TIME_END_2023_R2_1_0000_TRANSFORM_none_LOSS_l1_2milParameters_RESULTS/coordinates_1mil_2ndThird.npy"
_2milTransformerPredictions="/home/vfourel/SOCProject/SOCmapping/SimpleTransformer/final_transformer_model_MAX_OC_150_TIME_BEGINNING_2007_TIME_END_2023_R2_1_0000_TRANSFORM_none_LOSS_l1_2milParameters_RESULTS/predictions_1mil_2ndThird.npy"
_20kTransformerCoordinates="/home/vfourel/SOCProject/SOCmapping/SimpleTransformer/final_transformer_model_MAX_OC_150_TIME_BEGINNING_2007_TIME_END_2023_R2_1.0000_TRANSFORM_none_LOSS_l1_20kParameters_RESULTS/concatenatedResults/coordinates.npy"
_20kTransformerPredictions = "/home/vfourel/SOCProject/SOCmapping/SimpleTransformer/final_transformer_model_MAX_OC_150_TIME_BEGINNING_2007_TIME_END_2023_R2_1.0000_TRANSFORM_none_LOSS_l1_20kParameters_RESULTS/concatenatedResults/predictions.npy"
FoundationModelCoordinates="/home/vfourel/SOCProject/SOCmapping/results_prediction_41by41WindowSize/FoundationalModels/L1Loss_ZeroCenteredTarget/run2015_MAXOC150_v1/coordinates_1mil_2ndQuarter.npy"
FoundationModelPredictions="/home/vfourel/SOCProject/SOCmapping/results_prediction_41by41WindowSize/FoundationalModels/L1Loss_ZeroCenteredTarget/run2015_MAXOC150_v1/predictions_1mil_2ndQuarter.npy"
