
from mapping import create_prediction_visualizations


RandomForestCoordinates="/home/vfourel/SOCProject/SOCmapping/SimpleTimeModel/XGBoost/RandomForestFinalResults2023/coordinates_1mil_rf.npy"
RandomForestPredictions="/home/vfourel/SOCProject/SOCmapping/SimpleTimeModel/XGBoost/RandomForestFinalResults2023/predictions_1mil_rf.npy"
XGBoostCoordinates="/home/vfourel/SOCProject/SOCmapping/SimpleTimeModel/XGBoost/XGBoostFinalResults2023/coordinates_1mil_xgboost.npy"
XGBoostPredictions="/home/vfourel/SOCProject/SOCmapping/SimpleTimeModel/XGBoost/XGBoostFinalResults2023/predictions_1mil_xgboost.npy"
_2DCNNCoordinates="/home/vfourel/SOCProject/SOCmapping/2DCNN/finalResults2023/coordinates_1mil.npy"
_2DCNNPredictions="/home/vfourel/SOCProject/SOCmapping/2DCNN/finalResults2023/predictions_1mil.npy"
_3DCNNCoordinates="/home/vfourel/SOCProject/SOCmapping/3DCNN/finalResults2023/coordinates_1mil.npy"
_3DCNNPredictions="/home/vfourel/SOCProject/SOCmapping/3DCNN/finalResults2023/predictions_1mil.npy"
CNNLSTMCoordinates="/home/vfourel/SOCProject/SOCmapping/CNNLSTM/finalResults2023/coordinates_1mil.npy"
CNNLSTMPredictions="/home/vfourel/SOCProject/SOCmapping/CNNLSTM/finalResults2023/predictions_1mil.npy"
TemporalFusionTransformerPredictions="/home/vfourel/SOCProject/SOCmapping/TemporalFusionTransformer/finalResults2023/concatenatedResults/predictions.npy"
TemporalFusionTransformerCoordinates="/home/vfourel/SOCProject/SOCmapping/TemporalFusionTransformer/finalResults2023/concatenatedResults/coordinates.npy"
_2milTransformerCoordinates="/home/vfourel/SOCProject/SOCmapping/SimpleTransformer/final_transformer_model_MAX_OC_150_TIME_BEGINNING_2007_TIME_END_2023_R2_1_0000_TRANSFORM_none_LOSS_l1_2milParameters_RESULTS_2023/coordinates_1mil_2ndThird.npy"
_2milTransformerPredictions="/home/vfourel/SOCProject/SOCmapping/SimpleTransformer/final_transformer_model_MAX_OC_150_TIME_BEGINNING_2007_TIME_END_2023_R2_1_0000_TRANSFORM_none_LOSS_l1_2milParameters_RESULTS_2023/predictions_1mil_2ndThird.npy"
_20kTransformerCoordinates="/home/vfourel/SOCProject/SOCmapping/SimpleTransformer/final_transformer_model_MAX_OC_150_TIME_BEGINNING_2007_TIME_END_2023_R2_1.0000_TRANSFORM_none_LOSS_l1_20kParameters_RESULTS_2023/concatenatedResults/coordinates.npy"
_20kTransformerPredictions = "/home/vfourel/SOCProject/SOCmapping/SimpleTransformer/final_transformer_model_MAX_OC_150_TIME_BEGINNING_2007_TIME_END_2023_R2_1.0000_TRANSFORM_none_LOSS_l1_20kParameters_RESULTS_2023/concatenatedResults/predictions.npy"
FoundationModelCoordinates="/home/vfourel/SOCProject/SOCmapping/results_prediction_41by41WindowSize/FoundationalModels/L1Loss_ZeroCenteredTarget/run2015_MAXOC150_v1/coordinates_1mil_2ndQuarter.npy"
FoundationModelPredictions="/home/vfourel/SOCProject/SOCmapping/results_prediction_41by41WindowSize/FoundationalModels/L1Loss_ZeroCenteredTarget/run2015_MAXOC150_v1/predictions_1mil_2ndQuarter.npy"
